Repository yjk5309/OMP, pull requests merged in 2020-10, with the labels that each got.

#42 [#41] customer | 책 수량 데이터 추가 및 관련 페이지 수정
  customer/splitviews/BookBasketInsertView.py
  customer/splitviews/MyPageView.py
  customer/splitviews/OrderConfirmView.py
  customer/splitviews/OrderCreateView.py
  customer/splitviews/OrderDetailView.py
  customer/splitviews/OrderHistoryView.py
  customer/splitviews/OrderSheetCartView.py
  customer/splitviews/OrderSheetView.py
  customer/static/css/order_sheet.css
  customer/templates/book_basket.html
  customer/templates/book_detail.html
  customer/templates/order_confirm.html
  customer/templates/order_detail.html
  customer/templates/order_history_list.html
  customer/templates/order_sheet.html
Labels: documentation

#37 [#34] book DB수정 & 카테고리 수정
  customer/splitviews/OrderConfirmView.py
  customer/splitviews/OrderDetailView.py
  customer/templates/category.html
  customer/templates/category_result.html
  customer/templates/order_sheet.html
Labels: bug, documentation

#39 [#38] 마이페이지 관련 파일 수정
  customer/static/css/mypage.css
  customer/templates/book_basket.html
  customer/templates/mylist.html
  customer/templates/order_history_list.html
  customer/templates/order_sheet.html
  customer_accounts/templates/info_modify.html
  customer_accounts/templates/password_check.html
  customer_accounts/templates/password_modify.html
  customer_accounts/templates/register.html
  customer_accounts/templates/user_delete.html
Labels: documentation

#45 customer | 주문 수량 추가
  customer/splitviews/OrderCreateView.py
  customer/templates/order_sheet.html
Labels: enhancement
